// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlQ04Mkibw_3sJZ4IfZK2pAMwzPETLAO8',
    appId: '1:353945851143:android:592c2cb264e56eab6c21a2',
    messagingSenderId: '353945851143',
    projectId: 'va-de-rumba',
    storageBucket: 'va-de-rumba.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-EO6zKiTdlyRhlj5F4j_a4tRj_Wxt0KQ',
    appId: '1:353945851143:ios:3f8494591bdba4666c21a2',
    messagingSenderId: '353945851143',
    projectId: 'va-de-rumba',
    storageBucket: 'va-de-rumba.firebasestorage.app',
    iosBundleId: 'com.vaderumba.gestion',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0DrWRG4JLWHSX2vk5zat6eVxxKs8GfvY',
    appId: '1:353945851143:web:7c27b29224e687476c21a2',
    messagingSenderId: '353945851143',
    projectId: 'va-de-rumba',
    authDomain: 'va-de-rumba.firebaseapp.com',
    storageBucket: 'va-de-rumba.firebasestorage.app',
    measurementId: 'G-0DXD34H6CZ',
  );
}
